import { Application } from '../declarations';
import addresses from './addresses/addresses.service';
import authmanagement from './authmanagement/authmanagement.service';
import cartItems from './cart-items/cart-items.service';
import carts from './carts/carts.service';
import categories from './categories/categories.service';
import championLikes from './champion-likes/champion-likes.service';
import championRates from './champion-rates/champion-rates.service';
import champions from './champions/champions.service';
import eventComments from './event-comments/event-comments.service';
import eventLikes from './event-likes/event-likes.service';
import eventRates from './event-rates/event-rates.service';
import events from './events/events.service';
import exerciseComments from './exercise-comments/exercise-comments.service';
import exerciseLikes from './exercise-likes/exercise-likes.service';
import exerciseRates from './exercise-rates/exercise-rates.service';
import exercises from './exercises/exercises.service';
import mailer from './mailer/mailer.service';
import options from './options/options.service';
import productComments from './product-comments/product-comments.service';
import productFlavors from './product-flavors/product-flavors.service';
import productRates from './product-rates/product-rates.service';
import products from './products/products.service';
import productSizes from './product-sizes/product-sizes.service';
import slides from './slides/slides.service';
import sports from './sports/sports.service';
import stories from './stories/stories.service';
import storyComments from './story-comments/story-comments.service';
import storyLikes from './story-likes/story-likes.service';
import storyRates from './story-rates/story-rates.service';
import storyViews from './story-views/story-views.service';
import users from './users/users.service';
// Don't remove this comment. It's needed to format import lines nicely.

export default function (app: Application): void {
  app.configure(addresses);
  app.configure(authmanagement);
  app.configure(cartItems);
  app.configure(carts);
  app.configure(categories);
  app.configure(championLikes);
  app.configure(championRates);
  app.configure(champions);
  app.configure(eventComments);
  app.configure(eventLikes);
  app.configure(eventRates);
  app.configure(events);
  app.configure(exerciseComments);
  app.configure(exerciseLikes);
  app.configure(exerciseRates);
  app.configure(exercises);
  app.configure(mailer);
  app.configure(options);
  app.configure(productComments);
  app.configure(productFlavors);
  app.configure(productRates);
  app.configure(products);
  app.configure(productSizes);
  app.configure(slides);
  app.configure(sports);
  app.configure(stories);
  app.configure(storyComments);
  app.configure(storyLikes);
  app.configure(storyRates);
  app.configure(storyViews);
  app.configure(users);
}
